enum AppPermission {
  viewAssignedVehicle,
  receiveVehicle,
  returnVehicle,
  updateMileage,
  createFuelRecord,
  createFieldReport,
  viewPersonnel,
  managePersonnel,
  viewReports,
  approveOperations,
  manageUsers,
  assignTechnicalWork,
  manageTeamPermissions,
}
